@echo on
cd ..
cd ..
copy out\GetRuntimePack\bin\Debug\net6.0\win-x86\runtime-pack-dir.txt out\native\generated\wincoretpa.h 
:: C:\Users\user\.nuget\packages\microsoft.netcore.app.runtime.mono.win-x86\6.0.8\runtimes\win-x86\native
powershell -Command "(gc ./out/native/generated/wincoretpa.h) -replace '\\' , '\\' | Out-File -encoding ASCII ./out/native/generated/wincoretpa.h"
powershell -Command "(gc ./out/native/generated/wincoretpa.h) -replace '\\6.0.8', '\\6.0.8\\runtimes\\win-x86\\native\\System.Private.Corelib.dll ""' | Out-File -encoding ASCII ./out/native/generated/wincoretpa.h"
powershell '#define CORELIB_FULL_PATH """' + (Get-Content "./out/native/generated/wincoretpa.h" -Raw) | Set-Content "./out/native/generated/wincoretpa.h"
echo // Do not edit (auto-generated by wgen-corelib.bat) >>  "./out/native/generated/wincoretpa.h"
exit 0
